### ISSUE TITLE
Feature priority TODO

### ISSUE THREAD

**Issue by DeyvidA** [DeyvidA/reactTodo#6]
add estate for each one the task that express level of priority

- [x] create state priority and default
- [x] asign state for each one the task
- [x] add option to asign priority 
- [x] add button trigger option to app priority state.

2:30 H
